# Description: Workflow that allow you to build and deploy java maven application using git flow.
# Version 1.2.0
# GitHub Code: https://github.com/Iberia-Ent/software-engineering--workflow-java-maven
# Git Flow Code: https://github.com/Iberia-Ent/software-engineering--git-flow-template
name: CICD_JAVA_MAVEN

on:  
  push:  
    branches-ignore: [ main, develop, staging ]    
  pull_request:  
    branches: [ develop, staging ]
    types:  [ opened, reopened, closed ]
  release:
    types:
      - created
            
jobs:
  Init:
    name: Set up variables
    runs-on: ubuntu-latest    
    outputs:
      ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}
      LEVEL_READ_FILE: ${{ env.LEVEL_READ_FILE }}
      
    steps:
    - uses: actions/checkout@v2
        
    - name: Set Up ci-config File
      run: |
        if [ ${{ github.event_name }} = pull_request ] && [ ${{ github.event.pull_request.merged }} ] && ( [ ${{ github.ref }} = develop ] ) || [ ${{ github.event_name }} = push ]
        then                  
            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            echo DATA_JSON_FILE DEV: "$DATA_JSON_FILE"
            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            ENVIRONMENT_NAME=Integration
            echo ENVIRONMENT_NAME=Integration >> $GITHUB_ENV            
            echo LEVEL_READ_FILE=.int >> $GITHUB_ENV
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        elif [ ${{ github.event_name }} = pull_request ] && [ ${{ github.head_ref }} = develop ] && ( ( [ ${{ github.event.action }} = opened ] || [ ${{ github.event.action }} = reopened ] ) && [ ${{ github.base_ref }} = staging ] ) || ( [ ${{ github.ref }} = staging ] && [ ${{ github.event.pull_request.merged }} ] )
        then            
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            echo DATA_JSON_FILE PRE: "$DATA_JSON_FILE"
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            ENVIRONMENT_NAME=Preproduction            
            echo LEVEL_READ_FILE=.pre >> $GITHUB_ENV
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        elif ( [[ ${{ github.ref }} == refs/tags/v* ]] || [[ ${{ github.ref }} == refs/tags/HOTFIX_* ]] && [ ${{ github.event_name }} = release ] )
        then            
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            echo DATA_JSON_FILE PRO: "$DATA_JSON_FILE"
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            ENVIRONMENT_NAME=Production            
            echo LEVEL_READ_FILE=.prod >> $GITHUB_ENV
            echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        fi
        
        echo ENVIRONMENT_NAME=$ENVIRONMENT_NAME >> $GITHUB_ENV
        echo ENVIRONMENT_NAME: "$ENVIRONMENT_NAME"
        
        if [ ! -z "$ENVIRONMENT_NAME" ]
        then
            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            echo ENVIRONMENT_NAME: "$ENVIRONMENT_NAME"
            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        elif ( [ ${{ github.event.action }} = opened ] || [ ${{ github.event.action }} = reopened ] && [ ${{ github.base_ref }} = staging ] ) 
        then
            exit 1
        fi
        
  CI:
    name: Continous Integration
    needs: [Init]
    if: ${{ needs.Init.outputs.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.Init.outputs.ENVIRONMENT_NAME }}
    outputs:
      CODEARTIFACT_AUTH_TOKEN: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
      
    steps: 
    - uses: actions/checkout@v2

    - name: Loading Environment Variables
      uses: Iberia-Ent/software-engineering--read-file-action@v1.0.0
      with:
        file-path: '.github/config/ci-config.json'
        level: '${{ needs.Init.outputs.LEVEL_READ_FILE }}'        

    - name: Set up JDK ${{ env.JAVA_JDK_VERSION }}
      uses: actions/setup-java@v2
      with:
        java-version: '${{ env.JAVA_JDK_VERSION }}'
        distribution: '${{ env.JAVA_DISTRIBUTION }}'
        cache: 'maven'

    - name: Configure AWS credentials from DevOps account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set Up CodeArtifact Token   
      run: |         
        echo CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ env.AWS_CODEARTIFACT_DOMAIN }} --domain-owner ${{ env.AWS_ACCOUNT_ID }} --query authorizationToken --output text --duration-seconds 900` >> $GITHUB_ENV
    
    - name: Build and Unit Test
      run: |
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
        echo "Compiling..."
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++"        
        mvn -B package --file pom.xml -s .github/config/settings.xml
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++"  

  CD:
    name: Continous Deployment
    needs: [Init, CI]
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged && (github.ref == 'develop' || github.ref == 'staging')) || (github.event_name == 'release' && (startsWith(github.ref, 'refs/tags/v') ||  startsWith(github.ref, 'refs/tags/HOTFIX_')))
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.Init.outputs.ENVIRONMENT_NAME }}
      url: '${{ env.DEPLOYMENT_URL }}'
    outputs:
      POM_VERSION: ${{ env.POM_VERSION }}
    env:
        CODEARTIFACT_AUTH_TOKEN: ${{ needs.CI.outputs.CODEARTIFACT_AUTH_TOKEN }}
    steps: 
    - uses: actions/checkout@v2

    - name: Loading Environment Variables
      uses: Iberia-Ent/software-engineering--read-file-action@v1.0.0
      with:
        file-path: '.github/config/ci-config.json'
        level: '${{ needs.Init.outputs.LEVEL_READ_FILE }}'  

    - name: Set up JDK ${{ env.JAVA_JDK_VERSION }}
      uses: actions/setup-java@v2
      with:
        java-version: '${{ env.JAVA_JDK_VERSION }}'
        distribution: '${{ env.JAVA_DISTRIBUTION }}'
        cache: 'maven'

    - name: Configure AWS credentials from DevOps account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set Up Pom Variables
      run: |
        ARTIFACT_ID_POM=`grep -oPm1 "(?<=<artifactId>)[^<]+" pom.xml`
        FINAL_NAME_POM=`grep -oPm1 "(?<=<finalName>)[^<]+" pom.xml`
        POM_VERSION=`grep -oPm1 "(?<=<version>)[^<]+" pom.xml`               
     
        echo ARTIFACT_ID_POM=$ARTIFACT_ID_POM >> $GITHUB_ENV
        echo FINAL_NAME_POM=$FINAL_NAME_POM >> $GITHUB_ENV
        echo POM_VERSION=$POM_VERSION >> $GITHUB_ENV
    
    - name: Packaging Application
      run: |
        mvn -B package --file pom.xml -s .github/config/settings.xml
    
    - name: Copying AppSpect into Output Directory
      run: |
        echo "Copying appsspect into package folder..."
        cp .github/config/appspec.yml dist/
        cp -r .github/config/hooks dist/
        mkdir dist/WAR
        mv -f dist/${{ env.FINAL_NAME_POM }}.war dist/WAR
        
    - name: Uploading Package to S3 Bucket
      run: |
        aws deploy push --application-name ${{ env.FINAL_NAME_POM }} --s3-location s3://${{ env.BUCKET_REPOSITORY }}/${{ env.FINAL_NAME_POM }}/${{ env.ARTIFACT_ID_POM }}-${{ env.POM_VERSION }}.zip --ignore-hidden-files --source dist/
     
    - name: Create CodeDeploy Deployment
      run: |
        aws deploy create-deployment --application-name ${{ env.FINAL_NAME_POM }} --deployment-config-name ${{ env.DEPLOYMENT_CONFIG_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} --s3-location bucket=${{ env.BUCKET_REPOSITORY }},key=${{ env.FINAL_NAME_POM }}/${{ env.ARTIFACT_ID_POM }}-${{ env.POM_VERSION }}.zip,bundleType=zip --description "Deployment generated automatically by: ${{ github.actor }}"

  TaggingRepository:
    name: Tagging Release Version into Repository
    needs: [CD]
    if: github.event_name == 'pull_request' && github.ref == 'staging' && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
    
      - name: Tagging to Staging Branch        
        run: |
            artifactTag=v${{ needs.CD.outputs.POM_VERSION }}
            echo "Tag Id: $artifactTag"
            messageTag="Tag $artifactTag created automatically new version of product."
            echo "Message Tag: $messageTag"            
            git config --global user.email ""
            git config --global user.name "${{ github.actor }}"
            git tag -a $artifactTag -m "$messageTag"
            git push --tags --progress
            echo "Push created with tag: $artifactTag"