# Description: Workflow that allow you to build and deploy java maven application using git flow. 
# Version 1.0.0
# GitHub Code: https://github.com/Iberia-Ent/software-engineering--java-maven-template
# GitHub Workflow: https://github.com/Iberia-Ent/software-engineering--workflow-java-maven
# Git Flow Code: https://github.com/Iberia-Ent/software-engineering--git-flow-template
name: CICD_JAVA_MAVEN

on:  
  push:  
    branches-ignore: [ main, develop, staging ]    
  pull_request:  
    branches: [ develop, staging ]
    types:  [ opened, reopened, closed ]
  release:
    types:
      - created
            
jobs:    
  JAVA:
    uses: Iberia-Ent/software-engineering--workflow-java-maven/.github/workflows/ci-cd-java-maven.yml@v1.0
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}