name: 'readfilecontent'
description: 'Read file content'
inputs:
  path:  # id of input
    description: 'File Path'
    required: false
    default: './version.json'
  level:
    description: 'Level where you want get info'
    default: 'dev'
    required: false
runs:
  using: "composite"
  steps: 
    - name: Read file
      run: |
        filepath="${{inputs.path}}"
        extension="${filepath##*.}"
        if [ "$extension" == "json" ]; then
            githubjson="$(jq -c '${{inputs.level}}' $filepath)"   
        else
            echo "Not valid format, you must use json file"
            exit -1
        fi
        json_data=$(echo -e "$githubjson")
        echo $json_data >> data.json
      shell: bash
    
    - name: Read json
      run: |
        import json
        import os
        with open('data.json') as file:
            data = json.load(file)
            for key, value in data.items():
                os.system('echo '+key+'='+value+' >> $GITHUB_ENV')
      shell: python
